### ISSUE TITLE
Sandbox appears to be hardcoded at wrong domain

### ISSUE THREAD

**Issue by MagicLegend** [aplazo/php.aplazo-magento-2-payment-gateway#93]
The sandbox in the code is at `api.aplazo.net`, but I believe this should be `api.aplazo.dev`. The `.net` domain does not appear to work when trying to get an authentication token. Am I correct in this?

Line causing the issue:
https://github.com/aplazo/php.aplazo-magento-2-payment-gateway/blob/dacc61111ad42beca1cdea469c1c832836d3727c/Helper/Data.php#L117

Response from `https://api.aplazo.net/api/auth`:

```json
{
    "timestamp": "2023-03-17T13:50:26.577+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/api/auth"
}
```

Response from `https://api.aplazo.dev/api/auth`:

```json
{
    "Authorization": "Bearer <Redacted_JWT>"
}
```

Also there is a small spelling mistake in `sandbox_mode` 😊

**Comment by alexmonsalvo** [comment]
This magento version doesn't work as PWA that's why we created your credentials as API configuration that does mean a generic integration in order to allow you to do test integration, in these case sandbox domain must to be .dev. 

For all Magento integration the sandbox is hardcode with .net domain and each domain have its own authentication token and just work in the domain that belongs. 

You already have authentication token for .dev domain, if you want to try this plugin please let us know to create authentication token for .net domain.

**Comment by MagicLegend** [comment]
@alexmonsalvo Thank you for your reply - I have answered in the email thread already. Maybe it'd be useful to have some documentation surrounding this, since I did not see this mentioned anywhere. I'll close the issue here.
